---
abstract: 'How long can you survive in a zombies attack'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>, Daniel Ruoso <ruoso@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Zumbis
requires:
  Carp: 1.0
  File::ShareDir: 1.02
  FindBin: 1.0
  Mouse: 0.64
  Path::Class: 0.19
  SDL: 2.510
  XML::Compile: 1.16
resources:
  homepage: http://search.cpan.org/dist/Games-Zumbis
  repository: http://github.com/ruoso/Zumbis
version: 0.02
